MS-AI-SCHOOL-5th-team6/InspirAItion

- .github/workflows/main_inspiraition.yml
- team6/settings.py
> https://inspiraition.net/ 도메인 연결

- team6/settings.py
www.inspiraition.net 추가
이전 테스트 hosts 삭제
> ALLOWED_HOSTS 정리

- .github/workflows/main_inspiraition.yml
- .gitignore
- app/templates/app/base.html
- static/css/style.css
- static/js/script.js
- team6/settings.py
프론트 css. js 파일 적용을 위한 프로젝트 구조 추가 및 셋팅 적용
> static 파일(css. js) 프로젝트 추가 및 setting 적용

- app/templates/app/index.html
- app/views.py
갤러리 기능:
- Post 모델에 공개 여부(is_public) 필드 추가
- 개인/공개 갤러리 뷰 구현
- 게시물 작성 폼에 공개 설정 옵션 추가
> #37 feat: 공개 갤러리 추가 및 홈페이지 단순화

- app/templates/app/about.html
- app/templates/app/ai_play.html
- app/templates/app/artgal.html
- app/templates/app/board.html
- app/templates/app/common/footer.html
- app/templates/app/common/frame.html
- app/templates/app/common/header.html
- app/templates/app/index.html
- app/views.py
html 구조화를 위한 기초 template 생성 및 적용
> #56 common template 생성 및 적용

- app/templates/app/ai_play.html
- app/templates/app/common/footer.html
- app/templates/app/common/header.html
- app/templates/app/main.html
- app/templates/app/post_detail.html
- app/urls.py
- app/views.py
- team6/settings.py
- util/common/azure_speech.py
> #51 AI 큐레이션 기능 개발을 위한 백엔드 프론트 개발

- app/templates/app/common/footer.html
> html templates 구조 변경 #55

- app/views.py
생성된 이미지의 url 을 dall-e  에서 team blob storage 로 변경
> #59 생성된 이미지 url 링크 관련 문제

- app/templates/app/post_detail.html
- app/urls.py
- app/views.py
> #71 AI 큐레이션 적용 및 기타 웹서비스 설정 업데이트

- app/templates/app/common/footer.html
- app/templates/app/post_detail.html
> #92 UI/UX 개선

- app/templates/app/create_post.html
- 제목, 내용, AI 이미지 생성 필수 입력 검증 로직 추가
- 각 필드별 구체적인 오류 메시지 alert 표시
- 폼 제출 전 validation 체크 구현
Closes #120
> fix: AI Playground 페이지 필수 입력 필드 검증 추가 (#120)

- app/templates/app/_post_list.html
- app/templates/app/common/footer.html
- app/templates/app/common/frame.html
- app/templates/app/common/header.html
- app/templates/app/gallery.html
- static/css/theme.css
- static/js/theme.js
- 헤더 네비게이션에 테마 전환 스위치 추가
- 다크모드 스타일 및 CSS 변수 설정
- 헤더와 푸터 색상 통일
- 드롭다운 메뉴 다크모드 스타일 적용
> feat: 다크모드 테마 기능 추가

- app/templates/app/common/frame.html
- app/templates/app/gallery.html
- app/views.py
- static/css/gallery.css
- 푸터가 화면 하단에 고정되지 않는 문제 해결
- 갤러리에서 태그 필터링 기능 개선
- 공개 갤러리에 좋아요 상위 3개 게시글을 포함하는 인기 게시글 슬라이더 추가
> fix: 푸터 하단 고정 레이아웃 수정 및 갤러리 기능 개선

- app/templates/app/home.html
- static/css/home.css
- static/js/home.js
- 음성 입력 버튼 UI 구현
- 일반/AI 음성 입력 드롭다운 메뉴 추가
- AI 음성 입력 아이콘 디자인 개선 (마이크+별)
> feat: 홈페이지에 음성 입력 기능 추가

- app/templates/app/about.html
- app/templates/app/home.html
텍스트만 수정했습니다. 폰트는 이후에 맘에드시는걸로 바꾸시면 될 것 같습니다
> #196 홈, 어바웃 페이지 설명 한글로 변경

- app/templates/app/auction/list.html
- app/urls.py
- app/views.py
- 경매 목록 페이지(auction/list.html) 구현
- 경매 정렬 기능 추가 (최신순/마감임박순/인기순)
- 실시간 남은 시간 표시 기능 추가
- timezone 관련 버그 수정
> feat: 경매 기능 구현 및 경매 목록 페이지 추가

- app/forms.py
- app/models.py
- app/templates/app/auction/detail.html
- app/templates/app/auction/list.html
- app/templates/app/common/header.html
- app/urls.py
- app/views.py
- Auction 객체 생성 시 post를 미리 할당하여 clean() 호출 문제 해결
- AuctionForm의 instance를 설정하여 validation 오류 방지
- models.py 수정 최소화
> fix: 경매 등록 시 post가 없는 문제 해결

- accounts/forms.py
- accounts/migrations/0005_chargecode.py
- accounts/migrations/0006_reset_all_balances.py
- accounts/migrations/0007_create_initial_charge_code.py
- accounts/migrations/0008_chargecode_and_usage_restructure.py
- accounts/models.py
- accounts/signals.py
- accounts/templates/accounts/profile_update.html
- accounts/urls.py
- accounts/views.py
- 모델 구조를 ChargeCode와 ChargeCodeUsage로 분리
- 각 유저별 한 번씩 충전코드 사용 가능하도록 수정
- team6 충전코드(5000원) 재생성
> refactor: 충전코드 모델 구조 수정

- app/models.py
- app/templates/app/auction/detail.html
- app/views.py
- 입찰 시 잔액 검증 및 처리 로직 추가
- 이전 입찰자 환불 처리 추가
- 경매 종료 시 판매자에게 금액 이전 로직 추가
> feat: 경매 입찰과 정산 로직 추가

- accounts/templates/accounts/signup.html
- requirements.txt
- 회원가입 페이지 디자인 개선
- 다크모드/라이트모드 호환성 추가
- 이용약관 부분 테마 호환 스타일링 적용
- 사이트 특성에 맞는 회원가입 헤더 문구 변경
- 소셜 로그인 버튼 추가 (작동 X)
> feat: 회원가입 페이지 UI 개선 및 테마 호환성 추가

- app/templates/app/_post_list.html
- app/templates/app/gallery.html
- static/css/gallery.css
- static/js/gallery.js
- 상단 슬라이더 디자인 톤다운 (제목과 작성자만 표시)
- 갤러리 아이템 디자인 개선 및 호버 효과 추가
- 태그 내비게이션 스타일 유지 및 기능 개선
- 경매 중인 아이템에 배지 추가
- 다크 모드 지원 개선
- 반응형 디자인 대응 강화
> style: 공개 갤러리 UI 개선

- app/templates/app/gallery.html
- static/css/gallery.css
- 다크모드에서 활성화된 태그가 잘 보이도록 수정
- 전체보기 버튼 클릭 시 검색어와 태그 필터 모두 초기화되도록 변경
- URL 구조 개선으로 필터링 초기화 기능 강화
> fix: 갤러리 태그 선택 및 전체보기 기능 개선

- app/templates/app/fullscreen_gallery.html
- 상단/하단 컨트롤 패널 추가
- 진행 상태 표시 바 기능 추가
- 썸네일 내비게이션 기능 추가
- 로딩 화면 및 도움말 팝업 구현
- 키보드 단축키 지원 추가
- 전환 효과 및 컨트롤 자동 숨김 기능 추가
- 음악 재생 및 볼륨 조절 기능 추가
> feat: 풀스크린 갤러리 UI 개선

- app/templates/app/auction/list.html
- app/templates/app/common/header.html
- app/templates/app/create_post.html
- app/templates/app/gallery.html
- app/templates/app/home.html
- app/views.py
- static/css/gallery.css
- 내비게이션 바에서 fullscreen 갤러리 항목 제거
- 개인/공개 갤러리에 전시관 입장 버튼 추가
> feat: 갤러리 전시관 입장 기능 추가

- app/templates/app/gallery.html
- app/templates/app/home.html
- app/templates/app/post_detail.html
- app/urls.py
- app/views.py
- 갤러리에서 '내 전시관' 버튼 클릭 시 내 소유 작품만 표시
- 내 소유 작품들만 보여주는 전체화면 갤러리 뷰 추가
- 공개 갤러리와 내 갤러리 구분하여 전시관 버튼 링크 분리
> feat: 내 전시관 기능 추가

- app/templates/app/auction/register.html
- app/templates/app/create_goods.html
- app/templates/app/goods_detail.html
- app/templates/app/goods_list.html
- app/views.py
- static/css/goods.css
- 선택적 주문 기능 구현 (체크박스로 상품 선택)
- 선택된 상품에 따른 금액 자동 계산 기능
- 50,000원 이상 구매시 무료배송 적용 구현
- 가상 주문 시스템임을 명시하는 알림 추가
- 다크모드 지원 개선
> feat: 장바구니 시스템 개선 및 UI 업데이트
